---

source_path: "{{ shared_path }}"
dest_path: "{{ shared_path }}"
local_asset_path: "../backups"

migrate_dirs:
  - images
  - files
  - spree
  - storage # Required when local storage is used instead of S3
  - system
