---

domain: openfoodnetwork.ie
host_id: ie-prod
rails_env: production

mail_domain: openfoodnetwork.ie

enable_nginx_logging: true

certbot_domains:
  - openfoodnetwork.ie
  - www.openfoodnetwork.ie
  - ubuntu-20.openfoodnetwork.ie # kept temporarily while some assets still load with this url (site logo)

# Enable external database access for third party integrations
postgres_listen_addresses:
  - '*'

custom_hba_entries:
  - "{{ custom_hba_metabase }}"
  - "{{ custom_hba_n8n }}"
  - "{{ custom_hba_new_n8n }}"
  - "{{ custom_hba_new_n8n_IPv6 }}"
